import { useLayoutEffect } from "react";

const es = {
  "Contato:": "Contacto:",
  "VAGAS LIMITADAS": "CUPOS LIMITADOS",
  "Cota de participacao empresarial": "Cuota de participación empresarial",
  "SUA EMPRESA": "SU EMPRESA",
  "NA FESTA MAIS": "EN LA FIESTA MÁS",
  "ESPERADA DO ANO": "ESPERADA DEL AÑO",
  "Posicione sua marca dentro do stand oficial do 53o aniversario de Saltos del Guaira, com exposicao, relacionamento e experiencia VIP durante toda a festa.": "Posicione su marca dentro del stand oficial del 53.º aniversario de Saltos del Guairá, con exposición, relacionamiento y experiencia VIP durante toda la fiesta.",
  "24 a 30 de Julho": "24 al 30 de julio", "7 dias de festa": "7 días de fiesta", "30.000+ visitantes": "30.000+ visitantes", "fluxo estimado": "flujo estimado", "Stand oficial": "Stand oficial", "presenca premium": "presencia premium",
  "Investimento": "Inversión", "Pacote completo com exposicao, coquetel VIP, networking e presenca durante os 7 dias.": "Paquete completo con exposición, cóctel VIP, networking y presencia durante los 7 días.", "GARANTA SUA PARTICIPACAO": "ASEGURE SU PARTICIPACIÓN",
  "APRESENTAÇÃO": "PRESENTACIÓN", "Estamos dedicados a": "Nos dedicamos a", "conectar sua marca": "conectar su marca", "ao público ideal.": "con el público ideal.",
  "Durante 7 dias, Saltos del Guairá estará em festa. Milhares de pessoas circularão pelo evento, autoridades estarão presentes e empresários estarão conectando oportunidades.": "Durante 7 días, Saltos del Guairá estará de fiesta. Miles de personas circularán por el evento, habrá autoridades presentes y empresarios conectando oportunidades.",
  "Sua empresa pode ocupar um espaço estratégico dentro do Stand Oficial da Secretaria de Indústria e Comércio e transformar visibilidade em relacionamento, vendas e novos negócios.": "Su empresa puede ocupar un espacio estratégico dentro del Stand Oficial de la Secretaría de Industria y Comercio y transformar visibilidad en relaciones, ventas y nuevos negocios.",
  "pessoas": "personas", "dias de exposição": "días de exposición", "stand oficial": "stand oficial", "PACOTE PREMIUM": "PAQUETE PREMIUM",
  "pessoas podem ver": "personas pueden ver", "sua marca.": "su marca.", "A festa reúne moradores, visitantes, autoridades, empresários e potenciais clientes em um dos momentos de maior circulação da cidade.": "La fiesta reúne a residentes, visitantes, autoridades, empresarios y clientes potenciales en uno de los momentos de mayor circulación de la ciudad.", "Sua marca presente no lugar certo, na hora certa.": "Su marca presente en el lugar correcto, en el momento correcto.",
  "OPORTUNIDADE REAL": "OPORTUNIDAD REAL", "Transformando presença em": "Transformando presencia en", "oportunidades reais.": "oportunidades reales.", "dias": "días", "Cada noite da programação representa uma oportunidade diferente de exposição, relacionamento e venda.": "Cada noche del programa representa una oportunidad diferente de exposición, relacionamiento y venta.", "O que cada dia de festa traz para sua empresa:": "Lo que cada día de fiesta aporta a su empresa:",
  "Visibilidade para milhares de pessoas": "Visibilidad para miles de personas", "Presença no stand oficial": "Presencia en el stand oficial", "Contato com autoridades e empresários": "Contacto con autoridades y empresarios", "Divulgação em canais estratégicos": "Difusión en canales estratégicos", "Experiência VIP para clientes convidados": "Experiencia VIP para clientes invitados",
  "Por que sua empresa": "¿Por qué su empresa", "precisa estar aqui?": "debe estar aquí?", "30.000+ PESSOAS": "30.000+ PERSONAS", "Sua marca exposta para milhares de potenciais clientes.": "Su marca expuesta ante miles de clientes potenciales.", "7 DIAS DE FESTA": "7 DÍAS DE FIESTA", "Todos os dias uma nova oportunidade de venda e relacionamento.": "Cada día, una nueva oportunidad de venta y relacionamiento.", "STAND OFICIAL": "STAND OFICIAL", "Presença em um espaço estratégico da Secretaria de Indústria e Comércio.": "Presencia en un espacio estratégico de la Secretaría de Industria y Comercio.", "AUTORIDADES PRESENTES": "AUTORIDADES PRESENTES", "Networking de alto nível com empresários, autoridades e clientes VIP.": "Networking de alto nivel con empresarios, autoridades y clientes VIP.", "ESPAÇO PREMIUM": "ESPACIO PREMIUM", "Stand 5m × 10m preparado para exposição e ativação comercial.": "Stand de 5 m × 10 m preparado para exposición y activación comercial.", "Uma oportunidade exclusiva para poucas empresas.": "Una oportunidad exclusiva para pocas empresas.",
  "BENEFÍCIOS EXCLUSIVOS": "BENEFICIOS EXCLUSIVOS", "O que sua empresa leva": "¿Qué obtiene su empresa", "ao participar?": "al participar?", "VISIBILIDADE TOTAL": "VISIBILIDAD TOTAL", "30.000+ pessoas vão ver sua marca durante os 7 dias de festa.": "Más de 30.000 personas verán su marca durante los 7 días de fiesta.", "NETWORKING DE ALTO NÍVEL": "NETWORKING DE ALTO NIVEL", "Autoridades, empresários, parceiros e clientes VIP no mesmo espaço.": "Autoridades, empresarios, socios y clientes VIP en el mismo espacio.", "MARCA EM TODOS OS CANAIS": "MARCA EN TODOS LOS CANALES", "Redes sociais, rádios, palco central e materiais do evento.": "Redes sociales, radios, escenario central y materiales del evento.", "PRODUTOS NO PALCO CENTRAL": "PRODUCTOS EN EL ESCENARIO CENTRAL", "Seus produtos em destaque para milhares de pessoas.": "Sus productos destacados ante miles de personas.", "COQUETEL PREMIUM INCLUSO": "CÓCTEL PREMIUM INCLUIDO", "Cerveja, whisky, refrigerante, água, churrasco e gastronomia para impressionar seus clientes.": "Cerveza, whisky, refrescos, agua, asado y gastronomía para impresionar a sus clientes.",
  "PROGRAMAÇÃO": "PROGRAMACIÓN", "7 dias de presença": "7 días de presencia", "e oportunidades.": "y oportunidades.", "ABERTURA OFICIAL": "APERTURA OFICIAL", "Presença de autoridades, imprensa e convidados.": "Presencia de autoridades, prensa e invitados.", "EXPOSIÇÃO E NEGÓCIOS": "EXPOSICIÓN Y NEGOCIOS", "Fluxo intenso de visitantes e oportunidades comerciais.": "Gran flujo de visitantes y oportunidades comerciales.", "COQUETEL E NETWORKING": "CÓCTEL Y NETWORKING", "Relacionamento com empresários, parceiros e clientes.": "Relacionamiento con empresarios, socios y clientes.", "ENCERRAMENTO ESPECIAL": "CIERRE ESPECIAL", "Feijoada, celebração e fortalecimento de conexões.": "Feijoada, celebración y fortalecimiento de conexiones.",
  "MAQUETE DO PROJETO": "MAQUETA DEL PROYECTO", "Um stand desenhado para": "Un stand diseñado para", "gerar presenca e negocio.": "generar presencia y negocios.", "As vistas 3D deixam claro onde a marca aparece e como o visitante circula: recepcao, exposicao, lounge VIP e pontos de ativacao integrados em um ambiente premium.": "Las vistas 3D muestran claramente dónde aparece la marca y cómo circula el visitante: recepción, exposición, lounge VIP y puntos de activación integrados en un ambiente premium.", "Vista frontal do stand": "Vista frontal del stand", "Entrada frontal": "Entrada frontal", "Distribuicao tecnica": "Distribución técnica", "Planta baixa do evento": "Plano del evento", "Perspectiva noturna": "Perspectiva nocturna", "Experiencia do publico": "Experiencia del público", "Area de exposicao": "Área de exposición", "presenca de marca em destaque": "presencia destacada de marca", "acesso direto ao stand": "acceso directo al stand", "Coquetel VIP": "Cóctel VIP", "relacionamento qualificado": "relacionamiento calificado", "Abrir": "Abrir", "em tela cheia": "en pantalla completa", "Fechar imagem em tela cheia": "Cerrar imagen en pantalla completa",
  "EXPERIÊNCIA VIP": "EXPERIENCIA VIP", "Coquetel premium": "Cóctel premium", "incluso.": "incluido.", "Impressione seus clientes com uma experiência completa todos os dias do evento.": "Impresione a sus clientes con una experiencia completa todos los días del evento.", "BEBIDAS": "BEBIDAS", "Cerveja": "Cerveza", "Refrigerante & Água": "Refresco y agua", "GASTRONOMIA": "GASTRONOMÍA", "Churrasco": "Asado", "Feijoada especial — dia 30/07": "Feijoada especial — día 30/07", "Mais do que expor sua marca, você terá um ambiente ideal para receber clientes, conversar com parceiros e gerar negócios com conforto e exclusividade.": "Más que exponer su marca, tendrá un ambiente ideal para recibir clientes, conversar con socios y generar negocios con comodidad y exclusividad.",
  "COMPARATIVO DE VALOR": "COMPARATIVO DE VALOR", "O que você recebe": "Lo que usted recibe", "vs. o que você paga.": "vs. lo que paga.", "Stand 5m × 10m por 7 dias": "Stand de 5 m × 10 m por 7 días", "Divulgação em redes sociais + rádio": "Difusión en redes sociales + radio", "Sorteio no palco central": "Sorteo en el escenario central", "Coquetel 7 dias com bebidas + comida": "Cóctel durante 7 días con bebidas + comida", "Valor estimado separado": "Valor estimado por separado", "SEU INVESTIMENTO NO PACOTE": "SU INVERSIÓN EN EL PAQUETE", "ECONOMIA DE": "AHORRO DE", "INVESTIMENTO QUE SE PAGA EM VENDAS": "INVERSIÓN QUE SE PAGA CON VENTAS", "Você não está comprando apenas um espaço. Está garantindo visibilidade, relacionamento, divulgação, experiência VIP e presença estratégica no evento mais esperado do ano.": "No está comprando solamente un espacio. Está garantizando visibilidad, relacionamiento, difusión, experiencia VIP y presencia estratégica en el evento más esperado del año.",
  "TUDO INCLUSO": "TODO INCLUIDO", "Pacote completo": "Paquete completo", "de participação.": "de participación.", "Exposição de produtos no stand oficial 5m × 10m": "Exposición de productos en el stand oficial de 5 m × 10 m", "Menção da marca nas comunicações do evento": "Mención de la marca en las comunicaciones del evento", "Espaço destacado e privilegiado dentro do stand": "Espacio destacado y privilegiado dentro del stand", "Sorteio de produtos no palco central": "Sorteo de productos en el escenario central", "Coquetel diário completo com bebidas e gastronomia": "Cóctel diario completo con bebidas y gastronomía", "Networking com autoridades, empresários e clientes": "Networking con autoridades, empresarios y clientes", "Presença durante 7 dias de festa": "Presencia durante 7 días de fiesta", "Toda a mídia individual para cada patrocinador será de responsabilidade do patrocinador!": "¡Todo el material multimedia individual de cada patrocinador será responsabilidad del patrocinador!", "Investimento único": "Inversión única", "Cinco Milhões de Guaranis": "Cinco millones de guaraníes", "ENTRE EM CONTATO AGORA": "CONTÁCTENOS AHORA",
  "Uma oportunidade criada para empresas que querem": "Una oportunidad creada para empresas que quieren", "crescer.": "crecer.", "Estar presente no maior evento da cidade é uma forma direta de fortalecer a marca e se aproximar de quem realmente compra.": "Estar presente en el mayor evento de la ciudad es una forma directa de fortalecer la marca y acercarse a quienes realmente compran.", "Empresário local": "Empresario local", "Durante a festa, empresários, autoridades e clientes circulam no mesmo ambiente. É o cenário ideal para gerar conexões.": "Durante la fiesta, empresarios, autoridades y clientes circulan en el mismo ambiente. Es el escenario ideal para generar conexiones.", "Parceiro comercial": "Socio comercial",
  "Sua marca merece ser vista por": "Su marca merece ser vista por", "Durante 7 dias, Saltos del Guairá estará em festa. Milhares de pessoas passarão pelo evento, autoridades estarão presentes, empresários estarão circulando e sua marca pode ocupar um espaço estratégico nesse cenário.": "Durante 7 días, Saltos del Guairá estará de fiesta. Miles de personas pasarán por el evento, habrá autoridades presentes, empresarios circulando y su marca podrá ocupar un espacio estratégico en este escenario.", "Não deixe sua empresa ficar de fora da maior oportunidade de visibilidade, relacionamento e negócios do ano.": "No permita que su empresa quede fuera de la mayor oportunidad de visibilidad, relacionamiento y negocios del año.", "ENTRE EM CONTATO AGORA E GARANTA SUA PARTICIPAÇÃO": "CONTÁCTENOS AHORA Y ASEGURE SU PARTICIPACIÓN",
  "Roteiro de Venda": "Guion de ventas", "Use este texto ao apresentar a proposta pessoalmente ou por ligação.": "Use este texto al presentar la propuesta personalmente o por teléfono.", "TEXTO SUGERIDO PARA APRESENTAÇÃO ORAL": "TEXTO SUGERIDO PARA PRESENTACIÓN ORAL", "Empresário, imagine sua marca exposta para 30.000 pessoas em 7 dias. Imagine fechar negócios com autoridades, empresários e clientes VIP, tudo no mesmo espaço, com cerveja, whisky e churrasco inclusos.": "Empresario, imagine su marca expuesta ante 30.000 personas durante 7 días. Imagine cerrar negocios con autoridades, empresarios y clientes VIP, todo en el mismo espacio, con cerveza, whisky y asado incluidos.", "Isso não é um gasto, é um investimento que se paga em vendas.": "Esto no es un gasto, es una inversión que se paga con ventas.", "Separado, tudo isso custaria mais de Gs 5.500.000. No nosso pacote, você paga apenas Gs 5.000.000.": "Por separado, todo esto costaría más de Gs 5.500.000. En nuestro paquete, usted paga solamente Gs 5.000.000.", "Mas corre, porque as vagas são limitadas!": "¡Pero apresúrese, porque los cupos son limitados!", "Não venda espaço. Venda oportunidade, visibilidade e retorno.": "No venda espacio. Venda oportunidad, visibilidad y retorno.",
  "Obrigado": "Gracias", "Sua empresa na festa mais esperada do ano.": "Su empresa en la fiesta más esperada del año.", "GARANTA SUA PARTICIPAÇÃO AGORA": "ASEGURE SU PARTICIPACIÓN AHORA", "Registros reais do evento": "Registros reales del evento", "Registro do evento": "Registro del evento", "Video do evento": "Video del evento", "24 A 30 DE JULHO": "24 AL 30 DE JULIO", "24-30 Julho": "24-30 julio",
  "Baixar PDF da Proposta": "Descargar PDF de la propuesta", "Preparando": "Preparando", "PDF pronto": "PDF listo", "Exportar proposta em PDF": "Exportar propuesta en PDF", "Nao foi possivel gerar o PDF. Tente novamente.": "No fue posible generar el PDF. Inténtelo nuevamente.", "SECRETARIA DE INDÚSTRIA E COMÉRCIO": "SECRETARÍA DE INDUSTRIA Y COMERCIO"
};

const originals = new WeakMap();
const entries = Object.entries(es).sort((a, b) => b[0].length - a[0].length);

function translate(value, language) {
  if (language !== "es" || !value) return value;
  return entries.reduce((result, [source, target]) => result.replaceAll(source, target), value);
}

function translateRoot(root, language) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    if (!originals.has(node)) originals.set(node, node.nodeValue);
    node.nodeValue = translate(originals.get(node), language);
  }
  root.querySelectorAll("[alt], [aria-label], [title], [placeholder]").forEach((element) => {
    ["alt", "aria-label", "title", "placeholder"].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return;
      const key = `data-original-${attribute}`;
      if (!element.hasAttribute(key)) element.setAttribute(key, element.getAttribute(attribute));
      element.setAttribute(attribute, translate(element.getAttribute(key), language));
    });
  });
}

export default function ProposalTranslator({ language, children }) {
  useLayoutEffect(() => {
    const root = document.getElementById("proposal-lp");
    if (!root) return undefined;
    document.documentElement.lang = language === "es" ? "es" : "pt-BR";
    translateRoot(root, language);
    const observer = new MutationObserver(() => translateRoot(root, language));
    observer.observe(root, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [language]);
  return children;
}
